"""Add security features and indexes

Revision ID: ec9c15efb2a8
Revises: bc65ec976c16
Create Date: 2025-10-26 09:08:01.289713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9c15efb2a8'
down_revision = 'bc65ec976c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))
        batch_op.create_index('idx_entry_created', ['created_at'], unique=False)
        batch_op.create_index('idx_entry_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_entry_user_mood', ['user_id', 'mood'], unique=False)
        batch_op.create_index('idx_entry_user_private', ['user_id', 'is_private'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_is_private'), ['is_private'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_mood'), ['mood'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_password_change', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('account_locked_until', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('last_password_change')

    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_entries_updated_at'))
        batch_op.drop_index(batch_op.f('ix_entries_title'))
        batch_op.drop_index(batch_op.f('ix_entries_mood'))
        batch_op.drop_index(batch_op.f('ix_entries_is_private'))
        batch_op.drop_index('idx_entry_user_private')
        batch_op.drop_index('idx_entry_user_mood')
        batch_op.drop_index('idx_entry_user_created')
        batch_op.drop_index('idx_entry_created')
        batch_op.drop_column('word_count')

    # ### end Alembic commands ###
